### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by JasonMWhite** [paramaggarwal/react-native-device-motion#1]
Could you flesh out the intended installation instructions a bit? I got the example app running, but couldn't figure out how to integrate it into my own.

**Comment by paramaggarwal** [comment]
The possible ways to get this working are all over the place right now as I can't find one single straight forward way to use a third party library. I would suggest copying the `.h` and `.m` file to your project and the `.js` file to your app.

**Comment by JasonMWhite** [comment]
Ah cool, thanks! Yeah, I see they're working on some kind of plugin management. I guess we just need to stay tuned.

**Comment by paramaggarwal** [comment]
You might have to link the standard `CoreMotion` framework in your Xcode project.
